theme: minima
title: My first website
author: yongchan
email: cyc9805@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website!
# social links
facebook_username: yongchanchun # DO NOT include the @ character, or else the build will fail!
github_username:  cyc9805 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
