theme: minima
title: My first website
author: yongchan
email: cyc9805@gmail.com
base_url: /gh-pages-minima-starter
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website!
  
# social links
facebook_username: yongchanskii # DO NOT include the @ character, or else the build will fail!
github_username:  cyc9805 # DO NOT include the @ character, or else the build will fail!
instagram_username: yongchanskii
show_excerpts: true 

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
