# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# site theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Outputting
permalink: /:categories/:title/
paginate: 5                                   # Defaults : 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  
# site setting
locale: "ko-KR"
title: "yongchan's website"
subtitle: "Welcome :)"
name: "yongchan"
description: "Welcome to my website! I'm currently rebuilding my website"
url: https://cyc9805.github.io
repository: "cyc9805/comments"
teaser: #/Users/yongchanchun/cyc9805.github.io/assets/image/profile1.JPG
logo: #"/Users/yongchanchun/cyc9805.github.io/assets/profile1.JPG"
masthead_title: "Welcome to my website!!"

# Site Author
author:
 name: "yongchanchun"
 avatar: "assets/image/profile1.JPG"
 bio: "I'm trying to post on a daily basis<br>this may be hard but **Nothing is gained without trying!**"

 location : "Seoul, South Korea"
 email:
 links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:cyc9805@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cyc9805"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/yongchanskii"
    - label: "Instagram"                            # 표시되는 이름입니다.
      icon: "fab fa-fw fa-instagram"                # fab fa-fw fa-{SNS NAME} 으로 해주세요.
      url: "https://www.instagram.com/yongchanskii"  # 개인 SNS 계정 링크를 기재하면 됩니다.

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:cyc9805@gmail.com
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:                                        # 이런식으로 url을 주석처리하면 노출되지 않습니다.
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/yongchanchun"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cyc9805"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/yongchanskii"
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# _config.yml, 32line 코드
comments:
  provider    : "utterances"                                # comment 처리 사이트 명칭 기재
              # false (default), "disqus", "discourse", "facebook"
              # "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname : #https-cyc9805-github-io                    # disqus의 shortname 기재
              # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  utterances:
    theme : "photon-dark"
    issue_term : "pathname"
              
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
      sidebar_main: true
  # _pages                      : 해당 하단 영역이 새로 추가되었습니다.
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


    
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
